---
title: "IPUMS & R"
author: "Bach Tran"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=T, echo = T}
library("ipumsr")
library("dplyr")
library("ggplot2")
library("stringr")
library("purrr")
library("sf")

#html
library("DT")
library("htmltools")
library("shiny")

```

## Import Data and Codebook

```{r setup, include=T, echo = T}
ddi = read_ipums_ddi("usa_00009.xml")
data = read_ipums_micro(ddi)
```

## Data Exploration
```{r explore, echo=T}
names(ddi)
ipums_view(ddi)
```
## Data wrangle (I will add more as time progresses)
```{r subset, echo=T}
college_regex = "^[123] yeear(s)? of college$" #define patern to relabel some college
data$EDUCD_level = data$EDUCD %>%
  lbl_collapse(~.val %/% 10)%>%
  lbl_relabel(
    lbl(2,"Less than High School") ~.val> 0 & .val <6,
    lbl(3, "High school") ~.lbl =="Grade 12",
    lbl(4, "Some college") ~str_detect(.lbl, college_regex),
    lbl(5, "College or more") ~.val %in% c(10,11)
  )%>%
  as_factor()
```


## Data Exploration pt.2
```{r wrangle, echo=T}
college_to_advance_degree_graph = data %>%
  group_by(YEAR)

ggplot(college_to_advance_degree_graph, aes(YEAR, ))

  summarise("% highest education attentment in population" =
              weeighted.mean()) 
    

levels(data$EDUCD)

  as_factor(ordered = T)
  lbl(6, "")
  ) %>%
  as_factor()


  )
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
